### PR TITLE
Add scroll to top functionality

### PR DESCRIPTION
**Pull request by DrJid**
- [x] Adds a method to scroll the main contentView to the top.

Since the contentView is private and I think it's okay to remain private, I needed a way to implement scroll to top such that it also accounts for whatever the header's height is.

### CODE REVIEW

**Comment by DrJid** [comment]
@maxep What did you think of this?

**Comment by maxep** [comment]
Thanks @DrJid for your contribution. I would rather have a declaration like this: 
`- (void)scrollToTopAnimated:(BOOL)animated`

**Comment by DrJid** [comment]
@maxep Good point! Added the `animated` parameter

**Comment by maxep** [comment]
Thanks!

**Pull request merged**
